// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitConfig() {
  return window['go']['main']['APP']['InitConfig']();
}

export function SynchronizeServer(arg1) {
  return window['go']['main']['APP']['SynchronizeServer'](arg1);
}

export function SynchronizeSettings(arg1) {
  return window['go']['main']['APP']['SynchronizeSettings'](arg1);
}
