// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitConfig():Promise<Record<string, string>>;

export function SynchronizeServer(arg1:boolean):Promise<void>;

export function SynchronizeSettings(arg1:Record<string, any>):Promise<void>;
